<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>

    <!-- 生成单文件 EXE -->
    <PublishSingleFile>true</PublishSingleFile>
    <!-- 关闭自包含：使用目标机器系统的 .NET 环境 -->
    <SelfContained>false</SelfContained>
    
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

</Project>
